## signup
POST http://localhost:7777/users/signup
Content-Type: application/json

{
    "matricula": 202567,
    "nome": "soṕh",
    "email": "sophia@gmail.com",
    "sexo": "feminino",
    "senha": "123456"
}

## findalll

## finduser

## edit

##delete