services:
  db:
    image: postgres:16
    container_name: postgresqlContainer
    environment:
      POSTGRES_USER: monitoriaIFRJ
      POSTGRES_PASSWORD: monitoria67
      POSTGRES_DB: monitoriasDB
    ports:
      - "6666:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: