services:
  db:
    image: postgres:18
    container_name: postgresqlContainer
    environment:
      POSTGRES_USER: ${DOCKER_USER}
      POSTGRES_PASSWORD: ${DOCKER_PASSWORD}
      POSTGRES_DB: ${DOCKER_DB}
    ports:
      - "${DOCKER_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: