@BACKEND_URL=http://localhost:7777
@ADM_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyMDI1MDAiLCJpYXQiOjE3ODQ1OTU0OTMsImV4cCI6MTc4NDU5NjM5M30.GiowcOR_GAbTQyKor9NQZKW4Ja2AbScpIb7NYXGx90I

### signup
POST {{BACKEND_URL}}/users/signup
Content-Type: application/json

{
    "matricula": 202500,
    "nome": "john",
    "email": "john@gmail.com",
    "sexo": "masculino",
    "senha": "123456"
}

### findall
GET {{BACKEND_URL}}/users
Authorization: Bearer {{ADM_TOKEN}}

### finduser
GET {{BACKEND_URL}}/users?name=alex
Authorization: Bearer {{ADM_TOKEN}}

### edit
PATCH {{BACKEND_URL}}/users/202500
Authorization: Bearer {{ADM_TOKEN}}
Content-Type: application/json

{
    "nome": "john abyner"
}

### delete
DELETE {{BACKEND_URL}}/users/202500
Authorization: Bearer {{ADM_TOKEN}}
